import type { EdaToolDefinition } from "../../contracts/src/index.ts";

const objectSchema = {
  type: "object",
  additionalProperties: true,
} as const;

export const JLCIRCUIT_TOOLS: EdaToolDefinition[] = [
  {
    name: "easyeda_health_check",
    description: "检查 JLCircuit Agent 与嘉立创EDA扩展之间的本地桥接状态。",
    riskLevel: "read",
    inputSchema: objectSchema,
    enabled: true,
  },
  {
    name: "easyeda_get_context",
    description: "读取当前项目、文档、选区以及原理图/PCB摘要。",
    riskLevel: "read",
    inputSchema: objectSchema,
    enabled: true,
  },
  {
    name: "easyeda_schematic_components",
    description: "按位号、图元 ID、关键词或区域读取当前原理图元件摘要和坐标。查询特定元件时必须使用过滤参数，避免无参数读取整页。",
    riskLevel: "read",
    beta: true,
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "匹配位号、名称或图元 ID 的关键词。" },
        reference: { type: "string" },
        references: { type: "array", items: { type: "string" } },
        primitiveId: { type: "string" },
        primitiveIds: { type: "array", items: { type: "string" } },
        left: { type: "number" },
        right: { type: "number" },
        top: { type: "number" },
        bottom: { type: "number" },
        limit: { type: "number", minimum: 1, maximum: 500, default: 200 },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_schematic_wires",
    description: "读取当前原理图中的导线几何、网络和图元 ID。",
    riskLevel: "read",
    beta: true,
    inputSchema: objectSchema,
    enabled: true,
  },
  {
    name: "easyeda_library_search_devices",
    description: "搜索嘉立创 EDA 器件库，返回可直接用于放置元件的 libraryUuid 与 uuid。优先使用完整型号或立创 C 编号，避免仅凭模糊名称选择器件。",
    riskLevel: "read",
    beta: true,
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", minLength: 1, description: "器件名称、完整型号或关键词；与 lcscIds 至少提供一项。" },
        lcscIds: { type: "array", minItems: 1, maxItems: 20, items: { type: "string" }, description: "精确查询的立创 C 编号数组。" },
        libraryUuid: { type: "string", description: "可选库 UUID；省略时使用系统库。" },
        limit: { type: "number", minimum: 1, maximum: 50, default: 10 },
        page: { type: "number", minimum: 1, default: 1 },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_run_drc",
    description: "运行当前文档的原生 DRC/ERC 检查。",
    riskLevel: "read",
    beta: true,
    inputSchema: objectSchema,
    enabled: true,
  },
  {
    name: "easyeda_canvas_locate",
    description: "将当前原理图或 PCB 画布定位到坐标或矩形区域。",
    riskLevel: "read",
    beta: true,
    inputSchema: {
      type: "object",
      properties: {
        x: { type: "number" },
        y: { type: "number" },
        scaleRatio: { type: "number" },
        left: { type: "number" },
        right: { type: "number" },
        top: { type: "number" },
        bottom: { type: "number" },
        tabId: { type: "string" },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_canvas_capture",
    description: "截取当前嘉立创EDA画布渲染结果，返回 PNG 图片供 AI 或用户视觉检查。",
    riskLevel: "read",
    beta: true,
    inputSchema: {
      type: "object",
      properties: { tabId: { type: "string" } },
    },
    enabled: true,
  },
  {
    name: "easyeda_canvas_capture_region",
    description: "定位到指定区域并截取画布图片，用于检查局部布局和连线可读性。",
    riskLevel: "read",
    beta: true,
    inputSchema: {
      type: "object",
      required: ["left", "right", "top", "bottom"],
      properties: {
        left: { type: "number" },
        right: { type: "number" },
        top: { type: "number" },
        bottom: { type: "number" },
        tabId: { type: "string" },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_post_write_verify",
    description: "执行写入后的上下文、DRC/ERC 和画布截图验证，返回语义证据与视觉证据。",
    riskLevel: "read",
    beta: true,
    inputSchema: {
      type: "object",
      properties: {
        left: { type: "number" },
        right: { type: "number" },
        top: { type: "number" },
        bottom: { type: "number" },
        tabId: { type: "string" },
        runDrc: { type: "boolean", default: true },
        capture: { type: "boolean", default: true },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_schematic_move_component",
    description: "移动原理图元件，并尝试保持连接导线端点；操作后返回连接校验结果。",
    riskLevel: "high",
    beta: true,
    inputSchema: {
      type: "object",
      required: ["primitiveId", "x", "y", "confirmWrite"],
      properties: {
        primitiveId: { type: "string" },
        x: { type: "number" },
        y: { type: "number" },
        preserveConnections: { type: "boolean", default: true },
        save: { type: "boolean", default: false },
        verifyVisual: { type: "boolean", default: true },
        tabId: { type: "string" },
        confirmWrite: { const: true },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_schematic_place_component",
    description: "按嘉立创器件库 UUID 和器件 UUID 在当前原理图放置元件。需要先从可信器件库查询结果获得 UUID，不得猜测。",
    riskLevel: "high",
    beta: true,
    inputSchema: {
      type: "object",
      required: ["libraryUuid", "uuid", "x", "y", "confirmWrite"],
      properties: {
        libraryUuid: { type: "string", minLength: 1 },
        uuid: { type: "string", minLength: 1 },
        x: { type: "number" },
        y: { type: "number" },
        subPartName: { type: "string" },
        rotation: { type: "number", default: 0 },
        mirror: { type: "boolean", default: false },
        addIntoBom: { type: "boolean", default: true },
        addIntoPcb: { type: "boolean", default: true },
        save: { type: "boolean", default: false },
        confirmWrite: { const: true },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_schematic_create_wire",
    description: "在当前原理图创建导线折线。line 使用扁平坐标数组 [x1,y1,x2,y2,...]。",
    riskLevel: "high",
    beta: true,
    inputSchema: {
      type: "object",
      required: ["line", "confirmWrite"],
      properties: {
        line: { type: "array", minItems: 4, items: { type: "number" }, description: "扁平坐标数组 [x1,y1,x2,y2,...]。" },
        net: { type: "string" },
        color: { type: "string" },
        lineWidth: { type: "number", minimum: 1, maximum: 10 },
        lineType: { type: "number", enum: [0, 1, 2, 3], description: "0 实线，1 虚线，2 点线，3 点划线。" },
        save: { type: "boolean", default: false },
        confirmWrite: { const: true },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_schematic_create_bus",
    description: "在当前原理图创建带名称的总线折线。",
    riskLevel: "high",
    beta: true,
    inputSchema: {
      type: "object",
      required: ["busName", "line", "confirmWrite"],
      properties: {
        busName: { type: "string", minLength: 1 },
        line: { type: "array", minItems: 4, items: { type: "number" }, description: "扁平坐标数组 [x1,y1,x2,y2,...]。" },
        color: { type: "string" },
        lineWidth: { type: "number", minimum: 1, maximum: 10 },
        lineType: { type: "number", enum: [0, 1, 2, 3], description: "0 实线，1 虚线，2 点线，3 点划线。" },
        save: { type: "boolean", default: false },
        confirmWrite: { const: true },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_schematic_create_rectangle",
    description: "在当前原理图创建矩形图形，可用于模块边框或说明框。坐标为左上角及宽高。",
    riskLevel: "high",
    beta: true,
    inputSchema: {
      type: "object",
      required: ["topLeftX", "topLeftY", "width", "height", "confirmWrite"],
      properties: {
        topLeftX: { type: "number" },
        topLeftY: { type: "number" },
        width: { type: "number", exclusiveMinimum: 0 },
        height: { type: "number", exclusiveMinimum: 0 },
        cornerRadius: { type: "number", minimum: 0, default: 0 },
        rotation: { type: "number", default: 0 },
        color: { type: "string" },
        fillColor: { type: "string", description: "填充色；none 表示不填充。" },
        lineWidth: { type: "number", minimum: 1, maximum: 10 },
        lineType: { type: "number", enum: [0, 1, 2, 3] },
        fillStyle: {
          type: "string",
          enum: ["None", "Solid", "Grid", "Horizontal Line", "Vertical Line", "Rhombic Grid", "Left Slash Line", "Right Slash Line"],
        },
        save: { type: "boolean", default: false },
        confirmWrite: { const: true },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_schematic_create_polygon",
    description: "在当前原理图创建闭合多边形图形，可用于不规则模块边框。line 为扁平坐标数组。",
    riskLevel: "high",
    beta: true,
    inputSchema: {
      type: "object",
      required: ["line", "confirmWrite"],
      properties: {
        line: { type: "array", minItems: 6, items: { type: "number" } },
        color: { type: "string" },
        fillColor: { type: "string", description: "填充色；none 表示不填充。" },
        lineWidth: { type: "number", minimum: 1, maximum: 10 },
        lineType: { type: "number", enum: [0, 1, 2, 3] },
        save: { type: "boolean", default: false },
        confirmWrite: { const: true },
      },
    },
    enabled: true,
  },
  {
    name: "easyeda_schematic_create_text",
    description: "在当前原理图创建说明文本。",
    riskLevel: "high",
    beta: true,
    inputSchema: {
      type: "object",
      required: ["x", "y", "content", "confirmWrite"],
      properties: {
        x: { type: "number" },
        y: { type: "number" },
        content: { type: "string", minLength: 1 },
        rotation: { type: "number", default: 0 },
        textColor: { type: "string" },
        fontName: { type: "string" },
        fontSize: { type: "number", exclusiveMinimum: 0 },
        bold: { type: "boolean", default: false },
        italic: { type: "boolean", default: false },
        underLine: { type: "boolean", default: false },
        alignMode: { type: "number", enum: [1, 2, 3, 4, 5, 6, 7, 8, 9], default: 1, description: "左上到右下的九宫格对齐模式。" },
        save: { type: "boolean", default: false },
        confirmWrite: { const: true },
      },
    },
    enabled: true,
  },
];

export const getTool = (name: string): EdaToolDefinition | undefined =>
  JLCIRCUIT_TOOLS.find((tool) => tool.name === name);
